apiVersion: networking.k8s.io/v1
kind: Ingress   # Manages external HTTP/HTTPS access to services
metadata:
  name: web-app-ingress
  annotations:
  # AWS LB Controller Annotations ####
  # 1. Controller Selection: Tell K8 to use AWS LB controller
  kubernetes.io/ingress.class: alb
  # 2. LB Type: Specifies that an ALB should be created (nlb for network load balancer)
  alb.ingress.kubernetes.io/scheme: internet-facing
  # 3. LB Protocol: Listin on port 443 and port 80
  alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
  # 4. Certificates: Reference existing ACM certificate ARN for HTTPS
  # CRITICAL: REPLACE with your actual certificate ARN, only affects pods routed through this ingress
  alb.ingress.kubernetes.io/certificate-arn: arn:aws:us-east-1:123456789012:certificate/uuid
  # Use a separate cert for each application or a wildcard for *.example.com
  # One ACM certificate must cover all hostnames if we have multiple paths/hosts inside a single ingress
  # 5. Redirect HTTP to HTTPS: enforces secure traffic
  alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  # 6. Target Group Configuration (Health Checks, etc)
  alb.ingress.kubernetes.io/healthcheck-path: /healthz
  alb.ingress.kubernetes.io/success-codes: '200'
spec:
  rules:
  - host: www.myapp.com # Domain for this ingress rule
    http:
      paths:
      # Rule 1: Redirect HTTP to HTTPS (uses action from annotations)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect # Reference the custom action defined in annotation
            port:
              name: use-annotation
      # Rule 2: Define HTTPS routing to app service
      - path: /
        pathType: Prefix # Matches all paths starting with /
        backend:
          service:
            name: web-app-service 
            port:
              number: 80 # Target Service Port (from service definition)