apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-data-access
  namespace: default
  annotations:
    # CRITICAL: This links the ServiceAccount to an AWS IAM Role ARN (defined in Terraform/IAM).
    # Any pod using this ServiceAccount will automatically assume this role.
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/ApiDataAccessRole
    # This role would contain permissions like S3 read/write, DynamoDB access, etc.